OrdererOrgs:

- Name: Orderer

  Domain: example.com

  Specs:

    - Hostname: orderer

PeerOrgs:

- Name: Mphasis

  Domain: mphasis.example.com

  Template:

    Count: 2

  Users:

    Count: 1

- Name: Dxc

  Domain: dxc.example.com

  Template:

    Count: 3

  Users:

    Count: 1